disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Yulong Ming's Homepage"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
# description = "My awesome website"
copyright = "Copyright (C) 2026 Yulong Ming <i@myl7.org>. [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted."

[params.author]
name = "Yulong Ming"
email = "i@myl7.org"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
#   headline = "I'm only human"
#   bio = "A little bit about you"
links = [
  { email = "mailto:i@myl7.org" },
  { link = "https://myl7.org/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { bluesky = "https://bsky.app/profile/username" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/myl7" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { itch-io = "https://username.itch.io" },
  #     { keybase = "https://keybase.io/username" },
  #     { keyoxide = "https://keyoxide.org/URI" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  #     { linkedin = "https://linkedin.com/in/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { matrix = "https://matrix.to/#/URI" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  { orcid = "https://orcid.org/0000-0002-6010-2661" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { signal = "https://signal.me/#eu/userid" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { spotify = "https://open.spotify.com/user/userid" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  { telegram = "https://t.me/myl7s" },
  #     { threads = "https://www.threads.net/@username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  #     { youtube = "https://youtube.com/username" },
  #     { ko-fi = "https://ko-fi.com/username" },
  #     { codeberg = "https://codeberg.org/username"},
  { link = "https://scholar.google.com/citations?user=J9cpSb0AAAAJ" },
  { link = "https://www.xiaohongshu.com/user/profile/64f3012b000000000603199d" },
]
